KEYWORDS_FOR_STATUS = ['current', 'status', 'upcoming', 'progress', 'live', 'completed', 'finished', 'games']
KEYWORDS_FOR_DASHBOARD = ['dashboard', 'referral', 'referrals', 'stats', 'record', 'history']
KEYWORDS_FOR_UNAVAILABLE_SPORTS = ['baseball', 'soccer', 'boxing', 'mma', 'golf', 'tennis']
STATUS_HOT = ["You are lit 🔥", "Nom nom 🍔", "You're ridin' hot 🤠", "We have lift off 🚀", "You're going off ⏰"]
STATUS_COLD = ["Goose 🥚"]